apiVersion: v1
kind: Secret
metadata:
  name: {{ template "fullname" . }}
  labels:
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    application: {{ template "fullname" . }}
    component: {{ template "name" . }}
type: Opaque
data:
{{- if .Values.cloud.azure }}
  azureClientId: {{ .Values.cloud.azure.clientId | b64enc }}
  azureClientSecret: {{ .Values.cloud.azure.clientSecret | b64enc }}
  azureTenantId: {{ .Values.cloud.azure.tenantId | b64enc }}
  azureSubscriptionId: {{ .Values.cloud.azure.subscriptionId | b64enc }}
{{- end }}
{{- if eq .Values.fileStorage.provider "azure" }}
  fileStorageAzureAccountName: {{ .Values.fileStorage.azure.accountName | b64enc }}
  fileStorageAzureAccountKey: {{ .Values.fileStorage.azure.accountKey | b64enc }}
{{- end }}
{{- if eq .Values.dbStorage.provider "mongodb" }}
  dbStorageMongodbUsername: {{ .Values.dbStorage.mongodb.username | b64enc }}
  dbStorageMongodbPassword: {{ .Values.dbStorage.mongodb.password | b64enc }}
{{- end }}
